### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [selwu/form#5]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

**Отлично** Все ветки присутствуют в репозитории.
**Отлично** Соблюдена версионность в проекте.

### Email
**Нужно исправить** регулярное выражение содержит синтаксические ошибки
http://i.imgur.com/FsMoqLx.png

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным

### Номер телефона
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

```
+7925900-90-90
+792590090-90
+7(925) 9009090
+7(925)9009090
```

### Адрес сайта
**Можно лучше** IP-адрес состоит из повторяющихся частей (блоков по 3 символа). Поэтому в регулярном выражении вместо дублирования их описания можно воспользоваться квантификатором указывающим число повторений для части.

**Нужно исправить** регулярное выражение содержит синтаксическую ошибку, связанную с избыточным экранированием спецсимволов
http://i.imgur.com/WT7pCpa.png

**Нужно исправить** следующие корректные кейсы не проходят валидацию
`http://some.test.yandex.ru` - адрес сайта может содержать поддомены

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`https://mysite.23` - tld не может состоять только из цифр

**Можно лучше** следующие некорректные кейсы проходят валидацию
`http://www.google.ru///////` - в пути количество слешей подряд должно быть ограничено 1

**Comment by zlocate** [comment]
Добрый день. Работа принята. Желаю вам успехов в дальнейшем прохождении курса!

**Comment by selwu** [comment]
Ок
